-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 10:58:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(100) NOT NULL,
  `postal_code` INT NOT NULL,
  `phone` INT NOT NULL,
  `gmail` VARCHAR(45) NOT NULL,
  `date_record` DATETIME NOT NULL,
  `recommendation of` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `glasses_sold` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(100) NOT NULL,
  `phone` INT NOT NULL,
  `fax` INT NOT NULL,
  `NIF` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`glasses_brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`glasses_brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `optica`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`glasses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand_id` INT NOT NULL,
  `graduation_r` FLOAT NOT NULL,
  `graduacion_l` FLOAT NOT NULL,
  `frame_type` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `color_vidreo_r` VARCHAR(45) NOT NULL,
  `color_vidreo_l` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `brand_id_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `optica`.`glasses_brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`order_detail` (
  `id` INT NOT NULL,
  `date_order` DATE NOT NULL,
  `glasses_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `bought_from` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_glasses_has_customer_customer1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_glasses_has_customer_glasses1_idx` (`glasses_id` ASC) VISIBLE,
  CONSTRAINT `glasses_id`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `optica`.`glasses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `optica`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bought_from`
    FOREIGN KEY (`bought_from`)
    REFERENCES `optica`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE optica;

INSERT INTO supplier (name, adress,phone, fax, NIF)
VALUES ('Alejandro','Espanya,Barcelona 08005, Calle Ramon Turro 10 esc A 4-3ª', 655538222, 1111, 111222333),
('Sara','Espanya,Barcelona 08007, Calle LLul 40 esc B 6-4ª', 633338222, 2222, 444555666),
('Maria','Espanya,Barcelona 08015, Calle Pujades 150 esc A 2-1ª', 644438222, 3333, 777888999);
 
INSERT INTO glasses (brand_id,graduation_r,graduacion_l,frame_type,color,color_vidreo_r,color_vidreo_l,price)
VALUES (4, 0.75, 0.5, 'F', 'Azul', 'Negro', 'Negro', 99.99),
(4 , 1.75, 1.5,'P', 'Azul', 'Negro', 'Negro', 199),
(5 , 2.75, 0.5, 'P', 'Rojo', 'Trasparente', 'Trasparente', 79.99),
(5 , 3.75, 5.5,'M',' Verde', 'Trasparente', 'Trasparente', 120.99),
(6 , 2.75, 7.5,'M', 'Amarillo', 'Negro',' Negro', 170.5);

INSERT INTO glasses_brand ( name, supplier_id)
VALUES ( 'Rayban',4),
('Nike',5),
('Adidas',6);

INSERT INTO customer( name, adress, postal_code, phone, gmail, date_record, recommendation_of)
VALUES ( 'Jose','Espanya,Barcelona,Calle Marina 34',08006,655588899,'jose@gmail.com','2022-01-01', null),
( 'Pepe','Espanya,Barcelona,Calle Marina 64',08007,655577799,'pepe@gmail.com','2022-01-02','Jose'),
( 'Manolo','Espanya,Barcelona,Calle Padilla 95',08004,65555599,'manolo@gmail.com','2022-01-03', null),
( 'Soraya','Espanya,Barcelona,Calle Mallorca 77',08003,652582299,'soraya@gmail.com','2022-01-04','Manolo');

INSERT INTO employee ( name, last_name, glasses_sold)
VALUES ('Juan','Perez', 4),
('Silvia','Rodriguez', 7),
('Marc','Saez', 3);

INSERT INTO order_detail ( date_order, glasses_id, customer_id, bought_from) 
VALUES ('2023-02-01', 16, 1, 1),
('2023-02-02', 17, 2, 1),
('2023-02-03', 18, 3, 2),
('2023-02-04', 20, 4, 3),
('2023-02-05', 17, 1, 1);


select * from supplier;
select * from glasses;
select * from glasses_brand;
select * from customer;
select * from employee;
select * from order_detail;

-- Llista el total de compres d’un client/a.

SELECT c.id, c.name, o.date_order, o.glasses_id FROM customer c right join order_detail o on c.id = customer_id where c.id = 1;

-- Llista les diferents ulleres que ha venut un empleat durant un any.

SELECT e.id, e.name, e.last_name, o.date_order, o.glasses_id FROM employee e right join order_detail o 
on e.id = bought_from where e.id = 1  AND  o.date_order between '2023-01-01' AND '2024-01-01';

-- Llista els diferents proveïdors que han subministrat ulleres venudes amb èxit per l'òptica.

SELECT  s.id , s.name, o.glasses_id, g.brand_id, gb.name FROM order_detail o

right join glasses g on glasses_id = g.id 

join glasses_brand gb on g.brand_id = gb.id

join supplier s on s.id = gb.supplier_id ;







