-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 13:32:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `youtube` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `youtube` ;

-- -----------------------------------------------------
-- Table `youtube`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `birthdate` DATE NOT NULL,
  `sex` ENUM('M', 'F') NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `postal_code` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `creation_date` DATE NOT NULL,
  `state` ENUM('public', 'private') NOT NULL,
  `user_playlist_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_playlist_id_idx` (`user_playlist_id` ASC) VISIBLE,
  CONSTRAINT `user_playlist_id`
    FOREIGN KEY (`user_playlist_id`)
    REFERENCES `youtube`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `video_title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  `file_name` VARCHAR(45) NOT NULL,
  `duration` INT NOT NULL,
  `thumbail` BLOB NULL DEFAULT NULL,
  `reproductions` INT NOT NULL,
  `state` ENUM('public', 'private', 'hidden') NOT NULL,
  `date_published` DATETIME NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `youtube`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`playlist_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`playlist_contents` (
  `list_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  INDEX `list_id_idx` (`list_id` ASC) VISIBLE,
  INDEX `video_id_idx` (`video_id` ASC) VISIBLE,
  PRIMARY KEY (`list_id`, `video_id`),
  CONSTRAINT `list_id`
    FOREIGN KEY (`list_id`)
    REFERENCES `youtube`.`playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `video_id`
    FOREIGN KEY (`video_id`)
    REFERENCES `youtube`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `youtube` ;

-- -----------------------------------------------------
-- Table `youtube`.`chanel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`chanel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `creation_date` DATE NOT NULL,
  `creation_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `creation_user_idx` (`creation_user` ASC) VISIBLE,
  CONSTRAINT `creation_user`
    FOREIGN KEY (`creation_user`)
    REFERENCES `youtube`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `user_comment_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_comment_id_idx` (`user_comment_id` ASC) VISIBLE,
  INDEX `video_id_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `user_comment_id`
    FOREIGN KEY (`user_comment_id`)
    REFERENCES `youtube`.`user` (`id`),
  CONSTRAINT `video_id`
    FOREIGN KEY (`video_id`)
    REFERENCES `youtube`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`i_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`i_like` (
  `comment_id` INT NOT NULL,
  `user_i_like_id` INT NOT NULL,
  `data_time` DATETIME NOT NULL,
  `like_dislike` ENUM('like', 'dislike') NOT NULL,
  PRIMARY KEY (`comment_id`, `user_i_like_id`),
  INDEX `user_like_id_idx` (`user_i_like_id` ASC) VISIBLE,
  CONSTRAINT `user_i_like_id`
    FOREIGN KEY (`user_i_like_id`)
    REFERENCES `youtube`.`user` (`id`),
  CONSTRAINT `comment_id`
    FOREIGN KEY (`comment_id`)
    REFERENCES `youtube`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`labels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`likes` (
  `videos_like_id` INT NOT NULL,
  `user_like_id` INT NOT NULL,
  `likes_dislikes` ENUM('like', 'dislike') NOT NULL,
  `data_hora` DATETIME NOT NULL,
  PRIMARY KEY (`videos_like_id`, `user_like_id`),
  INDEX `user_like_id_idx` (`user_like_id` ASC) VISIBLE,
  CONSTRAINT `user_like_id`
    FOREIGN KEY (`user_like_id`)
    REFERENCES `youtube`.`user` (`id`),
  CONSTRAINT `videos_like_id`
    FOREIGN KEY (`videos_like_id`)
    REFERENCES `youtube`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`published`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`published` (
  `labels_id` INT NOT NULL,
  `videos_labels_id` INT NOT NULL,
  INDEX `labels_id_idx` (`labels_id` ASC) VISIBLE,
  INDEX `videos_labels_id_idx` (`videos_labels_id` ASC) VISIBLE,
  PRIMARY KEY (`labels_id`, `videos_labels_id`),
  CONSTRAINT `labels_id`
    FOREIGN KEY (`labels_id`)
    REFERENCES `youtube`.`labels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `videos_labels_id`
    FOREIGN KEY (`videos_labels_id`)
    REFERENCES `youtube`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `youtube`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`subscription` (
  `chanel_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`chanel_id`, `usuario_id`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `youtube`.`user` (`id`),
  CONSTRAINT `chanel_id`
    FOREIGN KEY (`chanel_id`)
    REFERENCES `youtube`.`chanel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
